# Generated by Django 5.1.1 on 2024-09-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_group_management', '0001_initial'),
        ('users', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='homeworks',
            field=models.ManyToManyField(through='class_group_management.HomeworkAssignment', to='class_group_management.homework'),
        ),
    ]
