# Generated by Django 5.1.1 on 2024-09-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_group_management', '0002_classgroup'),
        ('users', '0003_customuser_homeworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_group_management.classgroup'),
            preserve_default=False,
        ),
    ]
