# Generated by Django 5.1.1 on 2024-09-28 22:50

from django.db import migrations


def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Create groups
    student_group, created = Group.objects.get_or_create(name='Student')
    teacher_group, created = Group.objects.get_or_create(name='Teacher')
    parent_group, created = Group.objects.get_or_create(name='Parent')

    # Assign permissions to groups (example)
    # Add permissions as needed
    # student_group.permissions.add(Permission.objects.get(codename='some_permission'))


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_remove_customuser_homeworks_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]
