# Generated by Django 5.1.1 on 2024-09-28 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_group_management', '0002_classgroup'),
        ('users', '0004_customuser_class_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='homeroom_teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='assigned_to',
            field=models.ManyToManyField(through='class_group_management.HomeworkAssignment', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
